
export const env = {
    SLACK_BOT_TOKEN: process.env.SLACK_BOT_TOKEN || "",
    SLACK_SIGNING_SECRET: process.env.SLACK_SIGNING_SECRET|| "",
    SLACK_CHANNEL_NOTI_TIMEOFF_ID: process.env.SLACK_CHANNEL_NOTI_TIMEOFF_ID || "",
    NEXT_PUBLIC_FIREBASE_API_KEY: process.env.NEXT_PUBLIC_FIREBASE_API_KEY || "",
    FIREBASE_ADMIN_SA_CLIENT_EMAIL: process.env.FIREBASE_ADMIN_SA_CLIENT_EMAIL || "",
    FIREBASE_ADMIN_SA_PRIVATE_KEY: process.env.FIREBASE_ADMIN_SA_PRIVATE_KEY || "",
    SLACK_CHANNEL_REVIEW_TIMEOFF_ID: process.env.SLACK_CHANNEL_REVIEW_TIMEOFF_ID || "",
    SHEET_ID: process.env.SHEET_ID || "",
    SHEET_NAME: process.env.SHEET_NAME || "",
    SLACK_BOT_PORT: process.env.SLACK_BOT_PORT || "",
}



